version: "3.8"
services:
  mangodb:
    image: mongo
    volumes:
      - data:/data/db
#     You can specify environments in a env config file
#    - is used when its a single value and not used whenthere is a key value pair
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: sam
#      MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
#    Docker Compose create the environment on its network
#    networks:
#      - goals-net

#  frontend:
#  backend:

#Named volumes should be referenced ere for reuses as well
volumes:
  data: